### ISSUE TITLE
Develop test suite

### ISSUE THREAD

**Issue by bblfish** [assemblee-virtuelle/pair#1]
The test suite should be able to take the ontology and the example files and verify that the ontology is consistent. It is not because pellet says that something is consistent that it actually is, as pellet does not know what the implicit constraints on the system are. So it requires making some restrictions explicit, even and sometimes adding test ones that are stronger than what we require, just in order to get make breakages more apparent.

**Comment by balessan** [comment]
Henry, do you have any resources about testing an ontology ?

I'd like to investigate this area.

**Comment by tfrancart** [comment]
Cleaning stuff here, I am closing this issue since it is not directly related to the ontology but rather to the tools. I think this would require the creation of SHACL or SHeX shapes file in order to validate data against a set of constraints.
