### ISSUE TITLE
Mapping E2M : ForWhat devrait sans doute se mapper sur un Goal dans la partie Extensionnelle

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#101]
Confusion entre ForWhat et Why (Finality) ?

Par rapport https://github.com/iPlumb3r/EcosystemMapping/blob/master/6_Ontologies/OWL-Ontology.md

@iPlumb3r : tu as un avis ?

**Comment by iPlumb3r** [comment]
En fait, dans E2M, j'ai eu besoin de distinguer le fait qu'un Agent et/ou qu'un Delivrable

**Comment by iPlumb3r** [comment]
De la même manière 2 produits peuvent s'adresser / être destiné au marché des fruits bio, mais l'un va le faire avec pour finalité principale la santé des consommateurs, l'autre pour assurer une économie circulaire dans une région particulière.
> Bref, l'idée était de découpler la "target" marché d'un produit de la raison (plus profonde) pour laquelle il existe

**Comment by GuillaumeAV** [comment]
Du coté de PAIR, je crois qu'il est pertinent qu'une orga, un event, un projet etc (extentionnel). puissent avoir un why et un for what ... Mais je suis peut-être à côté de l'enjeu qui vous intéresse ;-)
