### ISSUE TITLE
domain et range de concerned / concernedBy sur les Tasks pas défini : c'est quoi ?

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#106]

**Comment by GuillaumeAV** [comment]
Une tache de mon point de vue peut concerner un projet, un acteur, un event, une activité, un lieu ... Voire un document ?

**Comment by tfrancart** [comment]
Alors c'est une notion de "aboutness". Il faut généraliser la propriété "about" pour qu'elle s'applique à tous les sujets (en domain et en range), et virer concerned / concernedBy

**Comment by GuillaumeAV** [comment]
Ok avec ça !
