### ISSUE TITLE
Différence entre hasTask / taskOf et engagedTo / engages ?

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#107]
Les 2 couples de propriétés relient Agent et Task. Est-ce qu'elles veulent dire la même chose ? si oui, supprimer un doublon, si non, documenter la différence.

**Comment by GuillaumeAV** [comment]
Oups oui en effet c'est un doublon, on aurait pu aussi l'appeler assignedTo ;-) N'hésite pas à nommer le trux comme ca te semble préférable ;-)
