### ISSUE TITLE
Refactoring de Activity pour englober Event, Project et Task

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#110]
Je ne sais pas très bien ce que doit représenter une Activity, mais au sens général c'est tout ce qui peut être fait par un Agent, et cela doit donc regrouper Task, Project et Event.
Activity va ainsi devenir la cible de toutes les AgentInvolvement avec des Roles - sauf vers Agent, mais on est sur une notion plus particulière ici de "membership" plutôt que d'Activité.

![image](https://user-images.githubusercontent.com/2728945/81745716-93e51500-94a5-11ea-9ce5-5ae9045512a6.png)

**Comment by GuillaumeAV** [comment]
J'étais pas convaincu au premier abord, mais en lisant ces quelques lignes ca me semble en effet très pertinent .. 

Quelques exemples d'activités si besoin : 
- Production maraichère
- R&D sur le web sémantique 
- Organisation d'événements à destination des entrepreneurs ESS 
- Etc. 

Quelques exemples implications si besoin: 
- Responsable de production
- Chargé de projet
- Chargé de mission 
- Etc.
