### ISSUE TITLE
Clarifier Group vs. Organization (supprimer Group ?)

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#112]
Organization représentait "Organisation désigne un groupe d'individus s'étant rassemblés autour d'un objectif commun. Une organisation peut être formelle (structure juridique) ou informelle (groupe)."

Maintenant Group a été introduit. Est-ce la même chose ? La notion de Group est-elle plus générique qu'Organization ? plus spécifique ?

A mon avis il faut supprimer cette classe qui fait doublon avec Organization dans le sens qu'on lui a donné.

**Comment by tfrancart** [comment]
Le point : on a besoin d'identifier dans le modèle une seule classe de laquelle les Agent peuvent être membres. Quelle est cette classe ? je prend l'hypothèse que c'est Organization

**Comment by GuillaumeAV** [comment]
Sur la notion de groupe : 
En fait je crois qu'il est important qu'elle appraisse en tant que telle => Je n'ai pas documenté sa définitition sorry... 
Il s'agit de mon point de vue de modéliser les groupes de travail / les cercles / les départements etc. soit les structures intermédiaires des organisations .. Et qui peuvent d'ailleurs être trans-organisationnelles. 
Canous manquait beaucoup dans semapss v1 et la précédente ontologie de ne pas pouvoir mapper les groupes, mais seulement les organisations ...

**Comment by tfrancart** [comment]
On veut pouvoir représenter des relations d' "appartenance"/"membership" entre un Agent et un autre. A ce titre il faut qu'il y ait une seule notion dans PAIR qui représente "un truc auquel un Agent peut appartenir". Pour moi ce truc est la classe Organization.

On a bien documenté le fait qu'une Organization pouvait représenter un groupe informel, donc à mon sens Group doit être sous Organization. Pour clarifier on peut faire apparaitre "FormalOrganization" (qui représenterait les organistions ayant un statut défini, numéro d'enregistrement, etc.) au même niveau :

  - Organization
    - Group
    - FormalOrganization

Je ne sais pas bien où placer Ecosystem, serait-ce aussi une sous-classe d'Organization ? pas sûr.

**Comment by GuillaumeAV** [comment]
Pas d'objection, je me permets juste d'insister sur le fait que si j'ai proposé de faire apparaitre les groupes et les écosystèmes c'est dans la perspective de pouvoir exprimer la structure de nos communautés : 

* Micro : Individu
* Mezzo : Groupe de travail / Team / département etc. 
* Macro : Organisation 
* Meta : Ecosystèmes ... 

C'est ces 4 niveaux structurels qu'il me semble important de capturer.

Après je n'ai pas de préférence surla manière dont on peut le modéliser en OWL..
