### ISSUE TITLE
C'esy quoi les Roles dans les data properties ?

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#114]
critères, moyens_possibles, périmètre, raison_Etre, redevabilite ?

**Comment by GuillaumeAV** [comment]
Huum, j'ai traduit la substance des roles qu'on met en place sur le projet SemApps et [que tu trouveras ici](https://hackmd.io/SfSueIZlQmeD_ijfSyGtUw?both)
Tu verras un rôle se décrit par les critères, moyens_possibles, périmètre, raison_Etre, redevabilite ...

**Comment by tfrancart** [comment]
Trop top, OK. Je renomme un peu les propriétés pour les rendre plus jolies (pas d'accents, singulier, etc.)
