### ISSUE TITLE
Faire de Resource un concept Intentionel ? (ou confusion Resource/Deliverable/What)

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#115]
Pour moi, une "Resource" est tout ce qui peut être "neededBy" ou "offeredBy" par un Agent (ou une Activity, mais c'est un autre débat). A ce titre ca devrait être un Concept intentionnel, et "needs/neededBy" "offers/offeredBy" des relations au niveau intentionnel.

@GuillaumeAV @iPlumb3r : mais je m'égare peut-être, remettez-moi dans le droit chemin SVP si c'est le cas :-)

**Comment by iPlumb3r** [comment]
En fait le truc, c’est qu’on a besoin de gérer de nombreux Concepts, mais que nous n’avons pas forcement une infinité de Termes à notre disposition …
… et que si on souhaite architecturer PAIR avec le dichotomie Intention VS Extension parce que on la trouve pertinente, alors il va nous falloir déterminer et converger vers :
   - 1 terme préféré pour désigner le volet Intentionnel des « choses manipulées par les Agents » (as defined, as designed, as to be built, as built, …)
   - 1 terme préféré pour désigner le volet extensionel des « choses manipulées par les Agents » (atom-bsed, bit-based, energy-based, …)

Dans le cas de EM2, j’ai choisi :
   - Le Terme « Deliverable » pour désigner le volet « Intentionnel » de ces choses
> https://github.com/iPlumb3r/EcosystemMapping/blob/master/1_Semantic/Conceptionary/%40Deliverable.md
   - Le Terme « Resource » pour désigner le volet « Extensionel » de ces choses
> https://github.com/iPlumb3r/EcosystemMapping/blob/master/1_Semantic/Conceptionary/%C2%A7Resource.md
(Pour info, dans la toute 1ere version, j’avais fait le choix inverse ! 
Et puis finalement, j’ai choisi le Terme « Deliverable » pour l’aspect Intentionnel » car connoté d’une certaine « dynamique » (qui est « Produit » par les uns, et « Consommé » par les autres) indépendamment de sa nature …
(Entre-nous soit dit ce terme ne me satisfait pas totalement, mais je devais bien en choisir un)

Au final, j’ai envi de dire « peu importe » les termes que l’on choisi pour chacun des aspect …
Car l’essentiel est que le choix que l’on va faire pour PAIR soit expliqué et défini dans un Conceptionary … (Sans cela, chacun donne aux Termes que l’on utilise la signification qu’il à en tête à titre personnel)

**Comment by tfrancart** [comment]
Super, c'est clair. Comme PAIR s'appelle PAIR, il faut qu'on ait la notion de Resource quelque part :-)

Intuitivement j'ai eu la même idée que ton premier jet, c'est-à-dire utiliser le terme Resource pour la partie intentionnelle. Deliverable est connoté "industrie" je trouve
  
Dans EM2, il n'y a pas (encore ?) de relations an niveau extentionnel qui articule une em2:Resource avec d'autres Concepts extentionnels, correct ?

Dans PAIR il y a un certain nombre de propriétés qui portent sur la notion de pair:Resource (delivers, uses, usedBy, offers, needs) - actuellement donc au niveau Extentionnel, mais je pense que ces propriétés devraient "remonter" sur l'équivalent intentionnel de Resource (qui est donc dans PAIR actuellement la classe What).

**Comment by GuillaumeAV** [comment]
Perso je laisserai bien également ressource dans la partie extentionnelle.. 
Dans la partie intentionnelle, je verrai plutôt les concepts d'offre et de demande de ressources (market place) entre autres intenntions possibles ?

**Comment by iPlumb3r** [comment]
Dans EM2, il n'y a pas (encore ?) de relations an niveau extentionnel qui articule une em2:Resource avec d'autres Concepts extentionnels, correct ?
> Elles existent, mais ne sont pas encore documenté, car en phase de test.

![Capture d’écran 2020-05-13 à 13 06 13](https://user-images.githubusercontent.com/46555634/81805174-abaab080-951a-11ea-951f-08be14d6db06.png)

**Comment by iPlumb3r** [comment]
Dans PAIR il y a un certain nombre de propriétés qui portent sur la notion de pair:Resource (delivers, uses, usedBy, offers, needs) - actuellement donc au niveau Extentionnel, mais je pense que ces propriétés devraient "remonter" sur l'équivalent intentionnel de Resource (qui est donc dans PAIR actuellement la classe What).
> A mon sens toutes les relations sus-citées sont de niveau "Intensionel"

**Comment by tfrancart** [comment]
> Dans la partie intentionnelle, je verrai plutôt les concepts d'offre et de demande de ressources (market place) entre autres intenntions possibles ?

Si les notions d'offre et de demande sont intentionnelles, alors les propriétés needs / neededBy, offers / offeredBy doivent être au niveau intentionnel et donc se rattached à What et pas Resource.

Pour moi, par essence, une Resource peut être n'importe quoi offert/fourni/demandé/produit. Pour moi c'est l'équivalent de la notion de Deliverable EM2.

Au niveau extentionnel on devrait avoir des classes comme :

  - ProduitManufacturé
  - SoftwareAsAService
  - Software
  - Skill
  - Procédure

qui sont des notions extentionnelles.

Guillaume ta formulation _"Dans la partie intentionnelle je verrai plutôt les concepts d'offre et de demande de ressources entre autres intenntions possibles"_ me fait soupçonner (peut-être à tort) une incompréhension de ce qu'est le niveau intentionnel : il ne s'agit **pas** de décrire des _intentions que l'on prête aux entités du niveau extentionnel_, il s'agit de décrire _les mêmes entités_ selon une perspective générique et dynamique en fonction des liens qu'ils ont avec les autres entités du niveau intentionnel (les décrire pour ce qu'ils _font_ et pas pour ce qu'ils _sont_).

Ce soupçon d'incompréhension est aussi justifié par la relation "motivates" / "motivatedBy" que tu as mis dans PAIR, pour articuler le niveau extentionnel et intentionnel.

**Comment by tfrancart** [comment]
> Guillaume ta formulation "Dans la partie intentionnelle je verrai plutôt les concepts d'offre et de demande de ressources entre autres intenntions possibles" me fait soupçonner (peut-être à tort) une incompréhension de ce qu'est le niveau intentionnel

Evidemment, et ça va sans dire, l'incompréhension peut tout à fait se situer de mon côté :-)

**Comment by iPlumb3r** [comment]
Si les notions d'offre et de demande sont intentionnelles, alors les propriétés needs / neededBy, offers / offeredBy doivent être au niveau intentionnel et donc se rattached à What et pas Resource.

Pour moi, par essence, une Resource peut être n'importe quoi offert/fourni/demandé/produit. Pour moi c'est l'équivalent de la notion de Deliverable EM2.

Au niveau extentionnel on devrait avoir des classes comme :

    ProduitManufacturé
    SoftwareAsAService
    Software
    Skill
    Procédure

qui sont des notions extentionnelles.

> C'est exactement ça !
> Au passage, il me semble qu'on avait dit qu'avec l'approche INT vs EXT, le découpage 5WH avait perdu beaucoup de sont sens ...
