### ISSUE TITLE
Maintenance / modélisation de tous les sous-types

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#118]
![image](https://user-images.githubusercontent.com/2728945/81795059-f53fcf00-950b-11ea-8cbf-ed96c89218d0.png)

Vouloir avoir des listes de Type distincts pour chaque Sujet amène à dupliquer la taxonomie des Sujets comme taxonomie des Types. Ce n'est pas maintenable. A-t-on une solution ou un pattern de modélisation utile pour cela ? peut-on l'éviter ?

**Comment by GuillaumeAV** [comment]
Héhé cette question s'adresse à toi-même et à Bernard j'imagine ?
