### ISSUE TITLE
Inclure les controverses

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#132]
From : @ReX-AV-Gab  : Concernant la controverse, mon intuition était bonne ! Pour moi, c’est un incontournable de la v3. Un mauvais exemple, mais exemple parlant quand même : l’interopérabilité a pour solution le web sémantique & L’interopérabilité a pour controverse InfoCentral. Je suis prêt à discuter de la profondeur de la chose qui peut être vu comme la remise d’une évidence (pour sortir d’une impasse, pour innover, pour disrupter, pour changer de paradigme, pour transitionner). :)

Concernant la boîte, je pense qu’il pourrait se nommer boîte Action avec Idée-proposition (concept « Idée » avec la notion de projection) à l’intérieur et, peut-être, Idée-concept à l’extérieur de cette boîte Action (concept « Concept » sans projection sous-jacente). Je peux ajouter que dans la boîte Action, la projection est systématique (de l’idée-proposition au livrable en passant par l’initiative et le projet) si on imagine le chantier et l’activité hors de cette boîte Action.

J’avoue que j’ai l’impression que la notion de thème n’est pas pertinente dans notre cas.

**Comment by GuillaumeAV** [comment]
Yop ! J'ai intégré le concept de controverse dans une nouvelle version du diagramme ..

**Comment by ReX-AV-Gab** [comment]
Hello, Appelle-moi demain lundi de préférence avant 17h00. J'ai un premier éclairage sur le channel.
