### ISSUE TITLE
Les projets et événements ne devrait-ils pas hériter à la fois des classes acteur & activité ?

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#139]
@tfrancart tu te souviens c'est une discussion qu'on avait eue et une suggestion que tu avais faite ... 
On peut je crois (et c'est déja en partie le cas) factoriser les propriétés communes au niveau de la classe agent ... Mais ne peut-on pas en factoriser davantage ? 

N'hésite pas à me dire qu'elle est hors sujet et ne pas argumenter si c'est le cas ;)

**Comment by tfrancart** [comment]
Je me demande s'il n'y a pas confusion entre Acteur et Agent ? Les Projets et Evénements sont des _Agents_ au sens de PAIR, mais ce ne sont pas des _Acteurs_. Ca n'aurait pas tellement de sens je crois

**Comment by GuillaumeAV** [comment]
Oui oui ok :) Je la ferme du coup !
