### ISSUE TITLE
Ajouter publishedDate et updatedDate

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/pair#148]
Il me semble que c'est une donnée importante pour identifier quand une ressource a été ajoutée, et quand elle a été modifiée pour la dernière fois.

**Comment by tfrancart** [comment]
Oui, souvent par analogie avec DublinCore on dit `modifiedDate`

**Comment by GuillaumeAV** [comment]
Si on utilise DublinCore, peut-être alors récupérer ce genre de propriétés ?

**Comment by srosset81** [comment]
Côté SemApps on a décidé d'utiliser DublinCore. On peut fermer cette issue si vous voulez.

**Comment by GuillaumeAV** [comment]
Perso je pense qu'il serait pertinent de connecter PAIR à Dublin Core comme on l'a fait avec Skos, et comme on envisage de le faire avec Foaf ... 
Mais ce n'est peut-être pas prioritaire, bien que très utile je trouve pour caractériser les : 
* Contenus
Couverture
Description
Créateur
Type
Titre
Relation
Source
Sujet

* Propriété intellectuelle
Collaborateur
Créateur
Éditeur
Droits

* Données d'instanciation
Langue
Date
Format
Identifiant

**Comment by tfrancart** [comment]
Donc a dit que:
1. la frontière de PAIR s'arrête à décrire les liens entre les documents et le reste des entités, mais ne comprend pas le détail de la description des documents eux-mêmes.
2. par ailleurs comme Document est sous-classe de Resource cela donne la capacité de les décrires avec plein d'autres attributs de PAIR
3. les dates de modification des notices et autres attributs techniques SemApps devraient être déclarés dans une ontologie spécifique SemApps

Donc : on ferme.
