### ISSUE TITLE
Modéliser des relations réflexives 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#15]
Comment on fait ???

Cf comment dans l'ontologie PAIR 1.0 sur la relation "inclue"
"L'enjeu en termes de modélisation est de signifier qu'une idée peut inclure un idée, qu'un projet peut inclure un projet, qu'une ressource peut inclure une ressource. 

Par contre, je ne sais pas comment ne pas modéliser une idée n'inclue pas une projet, un projet n'inclue pas une ressource, etc. 

Comment poser ces restrictctions et ne modéliser que les relations d'inclusion II, PP, RR ?"

**Comment by tfrancart** [comment]
Soit déclarer des propriétés différents ideeInclueIdee, projetInclueProjet, ressourceInclueRessource.
Soit déclarer des restriction locales sur une propriété générique :
`Idee subclassOf (inclue only Idee)`
`Projet subclassOf (inclue only Projet)`
`Ressource subclassOf (inclue only Ressource)`

ou quelque chose dans le genre

**Comment by tfrancart** [comment]
On ferme ?

**Comment by GuillaumeAV** [comment]
Euuuh j'ai généralisé ces relations d'appartenance dans la summer 2020 => On en discute et on valide après review ?
