### ISSUE TITLE
ajouter la notion de materiel

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/pair#151]
Pour les besoins de Passerelle-Normandie, besoin de gérer la notion de matériel à un lieux. Cela pourrait être une data property ou un nouveau type avec relation au lieu.

**Comment by srosset81** [comment]
Il me semble que la notion de `Resource` peut largement s'appliquer dans ce cas ?
Avec des relations de type `produces`, `offers`, `uses`...

**Comment by srosset81** [comment]
Je vois que tu parles de lieux, mais dans ce cas la relation `hasLocation` semble suffisante pour indiquer qu'une ressource est disponible sur un lieu donné ?

**Comment by simonLouvet** [comment]
> Il me semble que la notion de `Resource` peut largement s'appliquer dans ce cas ?
> Avec des relations de type `produces`, `offers`, `uses`...

je suis assez d'accord, ca peut s'appliquer
