### ISSUE TITLE
Ajouter des references à des profil sur de sites web

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/pair#152]
Besoins de Passerelle-Normandie

Profil LinkedIn
Profil Fb
Profil Mastodon

**Comment by srosset81** [comment]
La notion de site web (`aboutPage`, `webPage`...) ne suffit-elle pas ? Qu'est-ce que tu utiliserais comme nom pour cette propriété ?

**Comment by simonLouvet** [comment]
Le besoin est de pouvoir savoir quel url correspond à quel plateforme et d'avoir une ergonomie / design spécifique à chaque réseau social. Je ne sais pas pour les noms de propriété.

**Comment by srosset81** [comment]
Tu ne pourrais pas simplement deviner le réseau social en fonction de l'URL ? C'est pas très compliqué à gérer côté métier.
Cela me semble lourd s'il faut créer un prédicat pour chaque type de réseau social.

**Comment by simonLouvet** [comment]
C'est envisageable. Peut être raisonner comme la relation entre person et orga avec une qualification/réification de la relation ?

**Comment by GuillaumeAV** [comment]
Effectivement aboutPage (Cardinalité 1-N) semble être la bonne propriété à utiliser, c'est en tout cas elle qu'on utilisait dans SemApps v1. 

En revanche on pourrait envisager de créer des data properties plus spécifiques, par exemple : 
- Calendrier qui pourrait pointer sur des google agenda ou autres 
- Gestion de projet qui pourrait pointer sur github, trello ou autres
- Communication externe qui pourrait pointer sur des twitter facebook ou autres ... 
- Etc;

Ce qui pourrait être très utile non ? :)

**Comment by tfrancart** [comment]
Typiquement dans SIOC on a une notion qui est le `UserAccount` qui identifie le compte de telle personne sur telle plate-forme (il existe depuis telle date, il a tels droits d'accès, etc...).
Cette notion n'existe pas dans PAIR

**Comment by GuillaumeAV** [comment]
Aah c'est pas mal ça ! Qu'est ce que tu suggères Thomas ... Créer des propriétés qui ressemblent à celles de SIOC ? Ou importer SIOC dans PAIR ?

**Comment by tfrancart** [comment]
Pas d'import selon notre politique de faire de PAIR une ontologie métier. Si on veut avoir cette notion il faut ajouter les déclarations de classes et de proprétés adéquates.

**Comment by GuillaumeAV** [comment]
@srosset81 je crois que vous êtes en train de résoudre le problème ici ? https://github.com/assemblee-virtuelle/semapps/issues/602

**Comment by srosset81** [comment]
> @srosset81 je crois que vous êtes en train de résoudre le problème ici ? [assemblee-virtuelle/semapps#602](https://github.com/assemblee-virtuelle/semapps/issues/602)

On permet juste d'indiquer plusieurs webPage, et il est prévu de deviner le type de webPage en fonction du nom de domaine. C'est à @simonLouvet de dire si cette solution répond au besoin exprimé dans cette issue.

**Comment by simonLouvet** [comment]
A priori oui, ca répond @srosset81 et @GuillaumeAV pour Passerelle Normandie si on la complète par du design (affichage d'un logo en fonction du domaine) comme le dit deb. @BastienSig bosse dessus à la fois pour passerelle et le noyau.
