### ISSUE TITLE
Ontologie auto-hébergée

### ISSUE THREAD

**Issue by jmvanel** [assemblee-virtuelle/pair#16]
Actuellement ceci renvoie une erreur : 
http://www.virtual-assembly.org/ontologies/1.0/pair#InitiativeOrMission

```
Nothing Found
Sorry, the post you are looking for is not available.
```

Idéalement, http://www.virtual-assembly.org/ontologies/1.0/pair# renverrait automatiquement sur : 
https://raw.githubusercontent.com/assemblee-virtuelle/pair/master/PAIR_1.0.owl.ttl

Mas au minimum, une procédure (script) doit permettre de le refaire à chaque modif' de PAIR_1.0.owl.ttl

**Comment by tfrancart** [comment]
Utilisation de https://github.com/dgarijo/Widoco pour générer une page de doc statique maintenant déployée sur le serveur à https://www.virtual-assembly.org/ontologies/pair, incluant la négociation de contenu.
