### ISSUE TITLE
Charger les ontologies foaf, schema etc

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#17]
De manière à avoir l'ensemble des propriétés et à ne pas en créer qui seraient déja là ... Et de manière en créer de l'interopérabilité ;-)

**Comment by tfrancart** [comment]
On a statué sur le fait que PAIR serait une ontologie pivot alignée avec d'autres, le seul import qui sera fait sera SKOS. On doit pouvoir fermer ce ticket.

**Comment by GuillaumeAV** [comment]
Je ferme !
