### ISSUE TITLE
Diagramme et modèle : documenter les types de ressources

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#175]
La classe ResourceType existe, ainsi que d'autres sous-classes de Type

**Comment by GuillaumeAV** [comment]
Pour les ressources, proposition à laquelle on avait abouti si ma mémoire est bonne : 
- On en lève donc les sous-classes actuelles
- On garde tout de même compétences
- On ajoute document 
- Et on gère les autres typologies de ressources avec les types ? 
- Si besoin de spécifier présicément des ressources particulières, on crée des modules, par exemple, une petite ontologie dédiée à la description des logiciels ... Etc?

**Comment by tfrancart** [comment]
En fait ResourceType existe, et il y a une restriction locale sur pair:hasSubjectType sur la classe Resource, dont je ne me souvenais plus. Donc c'est bon pour cette issue, il n'y a rien à faire.
