### ISSUE TITLE
IncludesRessource n'est pas une sous propriété de includesProjects

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#18]
Les mettre au même niveau...

**Comment by tfrancart** [comment]
Ne se retrouve pas dans la version Summer2019 de l'ontology, dérivée de master. Faut-il rappatrier cette propriété ?

**Comment by GuillaumeAV** [comment]
Est-ce que c'est toujours d'actualité ? je ne crois pas .. On ferme ?
