### ISSUE TITLE
Ajouter la relation participe à - inverse of Attendee

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#19]
Ce devrait être la propriété de base, de laquelle nous devrions être en mesure de déduire qu'un événement a x attendees ...
Le domain doit bien être un agent / acteur

**Comment by tfrancart** [comment]
On ne retrouve pas cette propriété dans la version Summer2019. Faut-il la rajouter ?

**Comment by GuillaumeAV** [comment]
On a une relation ternaire désormais ;-)
