### ISSUE TITLE
Ressource documentaire : Ajouter article

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#21]
Imaginons un individu publiant des PAIRs sur wpldp. A l'un de ses projets, par exemple Semantic forms, il voudra relier des ressources documentaires, comme par exemple, son dernier article concernant son projet... C'est pourquoi je me dis qu'il est pertinent de créer une sous classe de document qui serit article ..;

**Comment by tfrancart** [comment]
Faut-il ajouter la classe Article sous Document dans la prochaine version Winter2019 ?

**Comment by GuillaumeAV** [comment]
Huum c'est une question qu'on peut se poser pour la summer 2020 ! 

La question est sans doute de savoir, si on crée une classe ou si un document type suffit ? 

La notion d'article est sans doute suffisamment importante pour mériter une classe ? 
Et peut-être aussi la notion de note ?
