### ISSUE TITLE
Gérer les Skills et le matching autour des skills

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#22]
Il s'agit d'une propriété et non d'une classe ... 

http://smiy.sourceforge.net/cco/spec/cognitivecharacteristics.html#skill

Que choisir à la place ? Chez skos ? Chez dbpedia ? Chez cerif ?

**Comment by tfrancart** [comment]
N'apparait pas dans la version actuelle. On ferme le ticket ? quite à en rouvrir un autre pour traiter la notion de Skill ? (qui est très intéressante, HappyDev l'a aussi)

**Comment by GuillaumeAV** [comment]
Dans la summer 2020, je propose une relation hasSkill reliant des personnes à des skills. 

Je me demande par ailleurs si on offre / demande des compétences, ou des services basés sur des compétences => Dans quel cas on pourrait enlever la relation offre / demande entre personnes et compétences ... 

On en discute ?

**Comment by GuillaumeAV** [comment]
Je renomme l'issue ..
