### ISSUE TITLE
Supression des doublons et simplification ontologie

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#23]
# Simplification des classes

- Organisation : Supprimer les sous classes (asso, entreprises, coop, etc) et mettre un type en data property à la place.
- InitiativeOrMission : En double : Supprimer celle qui n'est pas rattachée à Projets
- La suite très bientôt ...

**Comment by tfrancart** [comment]
A priori on peut fermer ce ticket, on pourra traiter le sujet des Organisations lors de la prochaine version

**Comment by GuillaumeAV** [comment]
Je ferme !
