### ISSUE TITLE
determiner l'URL de l'ontologie

### ISSUE THREAD

**Issue by bblfish** [assemblee-virtuelle/pair#3]
Pour respecter le Linked Data il faudra que l'ontologie soit publié a l'URL des relations qui y sont nommées. Pour l'instant les relations, concepts etc. ont des URLs relatives. A terme il faudra publier l'ontologie quelque part. Ce n'est pas encore urgent mais ca va le devenir.

**Comment by balessan** [comment]
Quid de http://www.virtual-assembly.org/ontology/pair.ttl comme URL de publication ?

Est-ce qu'il y a un standard concernant les formats d'URLs de publications ou c'est open-bar ?

**Comment by jmvanel** [comment]
Nous avons ces "best practices" officielles du W3C :

http://www.w3.org/TR/swbp-vocab-pub/
http://www.w3.org/TR/ld-bp/
