### ISSUE TITLE
Auto-hébergement de pair

### ISSUE THREAD

**Issue by atantet** [assemblee-virtuelle/pair#31]
https://www.virtual-assembly.org/pair/ -> https://www.virtual-assembly.org/pair/0.4/PAIR_v0.4.owl
https://www.virtual-assembly.org/pair/0.4 -> https://www.virtual-assembly.org/pair/0.4/PAIR_v0.4.owl
https://www.virtual-assembly.org/pair/0.3 -> https://www.virtual-assembly.org/pair/0.3/PAIR_v0.3.owl

**Comment by tfrancart** [comment]
cf #16
