### ISSUE TITLE
pair:isKeywordOf : pas utile et dangereux en général

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#43]
En général on ne déclare pas cette relation inverse des mots-clés vers les objets, un mot-clé pouvant être utilisé pour des milliers d'entités. L'avoir dans l'autre sens (pair:hasKeyword) suffit.

**Comment by tfrancart** [comment]
Même chose pour pair:isSubjectOf, pair:isTopicOf, pair:isTypeOf

**Comment by tfrancart** [comment]
En fait il y pas mal de propriétés inverses dans l'ontologie pour lesquelles on peut se poser la question.

**Comment by tfrancart** [comment]
Summer2019 : remarque toujours valable mais pour l'instant on conserve ces propriétés inverses qui ont du sens pour du raisonnement (mais pas pour de l'affichage pour lequel il faudrait se baser sur des Shapes).

**Comment by GuillaumeAV** [comment]
Oups ! J'aurais du relire cette issue avant ... 
Je peux m'engager à les enlever toutes si besoins .. Je pense que ca ne prendra pas plus d'une heure .. 
Si ca permet d'alléger et de d'assurer une meilleure consistance à l'ontologie, ca vaut le coup !
