### ISSUE TITLE
Import spreadsheet file into Turtle file compliant to pair vocabulary

### ISSUE THREAD

**Issue by jmvanel** [assemblee-virtuelle/pair#5]

**Comment by tfrancart** [comment]
Je suis en train de faire le ménage. C'est encore d'actualité ou on peut fermer ? éventuellement on pourrait mettre au point des templates de tableau Excel basés sur PAIR à partir de SKOS-Play convert : http://labs.sparna.fr/skos-play/convert

**Comment by GuillaumeAV** [comment]
Je ferme !
