### ISSUE TITLE
pas de domain sur pair:publicationDate ?

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#53]

**Comment by tfrancart** [comment]
Summer2019 : pair:publicationDate n'existe plus, faut-il le réintégrer ?

**Comment by GuillaumeAV** [comment]
En effet, je ne l'ai pas trouvé :-) 

Avant de lire cette issue ...

- J'ai créé une classe Date qui m'apparait, au regard de l'utilisation que je fais d'un outil comme roam research, de cas d'usage tels que les carnets de laboratoires, fondamentale ...
- J'ai créé une relation hasEdtionDate et sa relation inverse editionDateOf : Avec l'idée que lpremière date d'édition pourrait constituer la date de publication, les dates suivantes d'édition pourrait être les dates de modifications. Avec l'idée également que ca pourrait être automatisé, voire même inféré (publication ou modification) ;-) 

Est-ce que ca vous parait pertinent ?
