### ISSUE TITLE
Distinction TangibleGood vs. IntangibleGood vraiment nécessaire et correcte ?

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#54]
> IntagibleGood : "Un bien n'ayant pas vraiment de réalité matérielle. Un logiciel ou une méthodologie par exemple."

Un logiciel a une réalité matérielle sous la forme d'une séquence d'octet sur un disque dur. Une méthodologie a une réalité matérielle sous la forme de documents et de procédures (sinon c'est un Service, la capacité par quelqu'un d'appliquer une méthodologie).
Je ne suis pas sûr que cette distinction soit juste, ni qu'elle soit nécessaire, étant donné que rien ne distingue ces 2 sous-classes en terme de propriétés (ou alors je rate quelque chose)

**Comment by iPlumb3r** [comment]
A mon sens "Intangible Good" est plus relatif à un "Service"

**Comment by tfrancart** [comment]
Summer2019 : question toujours valable. La question porte sur la nécessité de distinguer TangibleGood et IntangibleGood, et non la nécessité de distinguer Good et Service.

**Comment by iPlumb3r** [comment]
Il me semble que la réponse à la question est éminemment dépendante de l’usage que l’on souhaite en faire ...
Bernard

**Comment by iPlumb3r** [comment]
Les récentes reflexions (https://github.com/iPlumb3r/EntangledBootstrap/blob/master/1_Semantic/Model_FR.md) sur la dichotomie « Intention VS Extension » permettent de proposer une réponse plus élaborée. 

En effet, la nécessité de cette distinction (dans l’ontologie PAIR)  d’une part … … et le fait que cette distinction soit correcte ou pas d’autre part … … dépende totalement du point de vue que l’on adopte.

D’un point de vue « Intentionnel » : cette distinction est totalement inutile, car l’aspect intentionnel ne s’intéresse qu’à la finalité des choses indépendamment de leur nature
(Et donc, les caractéristiques des #TangibleGood et #IntangibleGood sont de ce point vu  strictement les mêmes)

D’un point de vue « Extensionel » : cette distinction est pertinente dans l’absolu (même si les termes « Tangible » et « Intangible » ne sont sans doute pas les mieux adaptés pour la différence que l’on voulait faire apparaitre initialement qui était plus destiné à distingues les objets physiques, des objets digitaux et des services => Cf schema ci-après d’un découpage « extensionel » général) 

Quand à la question « Cette distinction est-elle pertinente pour PAIR ? » : Le point reste ouvert !

![Capture d’écran 2020-02-19 à 19 21 06](https://user-images.githubusercontent.com/46555634/74936667-dd641d80-53ea-11ea-8b10-6fa28a009683.png)

**Comment by GuillaumeAV** [comment]
Helloo ! 
On est finalement partis sur une classification : Atom / Concept / Energy / Bit / Money -basedResource

De mon poit de vue ca peut être utile à des fins de classification .. Cela dit, je survivrai si on les enlève ;-) 

On en discute pendant la review ?
