### ISSUE TITLE
Notes sur l'articulation de PAIR + EB #1

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#65]
La dichotomie intentionnel / extentionnel permet de retrouver les notions d'Acteurs et les Ressources qu'on avait paradoxalement perdu dans PAIR. 

PAIR ne prend en compte que le domaine extentionnel et définie des "Personnality" + des Biens, Services etc.  

Dans nos réflexions, on envisageait de faire réapparaitre les Acteurs / Ressources par inférence : 
- Si une personality s'engage dans un projet, alors on peut en déduire qu'elle est un acteur / agent
- Si un bien ou service est "offert" ou "demandé" alors on peut en déduire qu'il constitue une ressource ... 

=> La distinction intentionnel / extentionnel peut-elle nous permettre de retrouver les notions d'Acteur et de Ressource dans PAIR ?

**Comment by tfrancart** [comment]
OK avec ça, en plus ça ne me semble pas difficile à implémenter

**Comment by iPlumb3r** [comment]
Effectivement, PAIR est une ontologie essentiellement orientée "Extensionel" ...
... et on avait prévu de s'appuyer sur le #Role joué par un #Topic (Personality, Good, ...) dans le contexte d'une relation particulière pour en déduire leur appartenance à d'autres classes (acteur/agent, resources, ...)

**Comment by iPlumb3r** [comment]
Je l'ai fermée par erreur ..
.. et ne parviens pas à la ré-ouvrir !?

**Comment by srosset81** [comment]
Voilà :-)

**Comment by iPlumb3r** [comment]
Oui, d'une certaine manière le niveau "Intentionel" du modèle PAIR devrait refaire apparaitre ces notions (d'Acteur et de Ressource) qui apparaissent sur le schema ci-après noté respectivement "Agent" et "Technology" (Termes différents, mais notions intentionnelles très proches !)

![Capture d’écran 2020-02-20 à 16 01 13](https://user-images.githubusercontent.com/46555634/74947448-2ae88680-53fb-11ea-9247-2fcbfc1aa496.png)

**Comment by iPlumb3r** [comment]
Pour être plus précis, avant l'introduction de la dichotomie "Intention VS extention", on avait comme levier principal pour faire des inférences que celui apporté par la dichotomie "Role VS Topic" (Concepts plus naturel en modélisation "à la Topic Maps" qu'en modélisation "à la OWL", mais conceptuellement très pertinent !)

L'idée était donc (puisque la V3 de PAIR est une ontologie exclusivement extensionnelle), d'utiliser le fait d'un #Topic joue un #Role particulier dans une relation spécifique pour inférer une nouvelle classe d'appartenance (e.g. cas d'une #Organisation impliquée dans un e#Projet, qui devient "de facto" un #Actor))

**Comment by iPlumb3r** [comment]
Avec l'introduction de la dichotomie "Intention VS Extension" on peux maintenant faire vivre "côte à côte" des classifications (et leur concepts associés) qui poursuivre des finalités différentes :

**Comment by iPlumb3r** [comment]
Force est de constater que : 
* d'une part, il y a une certaine analogie entre 
** la facette Intention à échelle "macro" et le Role à échelle "micro"
** la facette Extension à l'échelle "macro" et le Topic à l'échelle "micro"

**Comment by GuillaumeAV** [comment]
On a finalement fait apparaitre les notions d'acteurs et de ressource dans la partie extentionnelle de PAIR
A discuter pendant la review !

**Comment by iPlumb3r** [comment]
> On a finalement fait apparaitre les notions d'acteurs et de ressource dans la partie extentionnelle de PAIR
> A discuter pendant la review !

OK pour Ressource => C'est bien un sujet extensionnel
Pas OK pour Acteur => A mon sens c'est typiquement un sujet intentionel
