### ISSUE TITLE
PAIR + EB #2 - Offre & demande 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#66]
Tel que je comprends les concepts intentionnels de EB :
1- AsRequiredThing : En tant que chose requise
2- AsDefinedThing : en tant que chose définie
3- AsDesignedThing : en tant que chose conçue / Pas en tant que chose désignée ? 
4- AsToBeBuildThing : En tant que chose à construire

Je me demande si 1 et 4 n'ont pas quelque chose à voir avec la notion de demande ? 
Est-ce que par ailleurs la notion d'offre est présente dans EB ?

**Comment by iPlumb3r** [comment]
Oui, c'est tout à fait cela !
Plus d'explication ici sur ces invariants : https://www.linkedin.com/pulse/les-invariants-m%C3%A9tiers-du-plm-bernard-chabot/

Et OUI, le "As Designed" est bien "la chose conçue" (en terme de caractéristiques  techniques spécifiées attendues) ...
... en NON, ce n'est pas "la chose désignée" ;-)

Ta remarque est tout à fait exacte, ces concepts (également utilisé par Myriam pour l'ontoloie de DFC) : http://datafoodconsortium.org/blog/product-ontologies-how-business-invariants-apply-also-to-the-food-system
sont au coeur d'un formalisation des processus de demande et d'offre

**Comment by GuillaumeAV** [comment]
Excellent, je suggère de viser l'interconnexion d'un module PLM et d'un module market place avec PAIR pour l'automne, ce serait pas mal non ?
