### ISSUE TITLE
PAIR + EB #3 : 5WH

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#67]
Pourrait-on associer ?

- justified by (Finality) => What
- triggered by (Influencer) => Why
- allowed by (Mean) => How

Coté AV & co, je crois qu'on a un réel besoin d'ontologiser la raison d'être (Why et What) et le #CodeSocial (How) de nos PAIRs. 
Il n'y aurait pas des liens ?

**Comment by iPlumb3r** [comment]
Lorsque conçu pour les besoins de la cartographie d'écosystème "Decentralized Everything" le questionnement associé était plutôt le suivant :

**Comment by GuillaumeAV** [comment]
Résolu différemment : 
Les 5Wh sont à la fois classes et relations => A voir et discuter dans le cadre de la review
