### ISSUE TITLE
Reconsidérer le meta modèle de PAIR

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#68]
La structure 5WH est vraiment intéressante : 

Les classes instanciables y sont réparties en fonction de leur nature .. 
La classe Proposition se retrouve par exemple dans la classe abstraite Why ... 

Une proposition serait de rassembler au sein de WHAT, tout ce qui n'est pas personnality : 
- Projet
- Proposition
- Evenement
- Lieu (j'ai un doute sur les Lieux)
=> Parce chacune de ces choses est susceptible d'avoir un WHY, un HOW, un WHERE etc.

Structurer le HOW par #CodeSocial 

Structurer le WHY par la Vision  la raison d'être

**Comment by tfrancart** [comment]
- Project est actuellement sous How
- Event est actuellement sous When
- Proposal est actuellement sous Why
- Lieu/Place est actuellement sous Where

Je ne suis pas convaincu par ta proposition. Il ne faut pas confondre le niveau "Sujet Métier" et le sous-niveau WHAT. La notion de WHAT (pour moi) est équivalente à la notion de "Chose Physique". Ce n'est pas parce que les projets, propositions, évènements et lieux peuvent avoir des WHY / HOW / WHERE que cela en fait des WHAT.

**Comment by iPlumb3r** [comment]
Sans doute une excellente idée ...
... par contre, compte tenu du récent REX (Retour d'Expericence) sur un autre projet de cartographie d'écosystème (Cf https://github.com/iPlumb3r/EntangledBootstrap/blob/master/1_Semantic/Model_FR.md) , il me semble que la structure 5WH doit passer en arrière plan par rapport à la dichotomie "Intention VS Extension" pour plusieurs raisons :

**Comment by GuillaumeAV** [comment]
Je crois que la conjonction de vos 2 commentaires permettent de solutionner ma problématique ;-)

**Comment by GuillaumeAV** [comment]
Proposition périmée, la question ne se pose plus étant donné qu'on a abandonné le 5WH dans la partie extentionnelle...  Du coup je ferme l'issue ;-)
