### ISSUE TITLE
Des modules pour décrire les domaines métiers ... 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#70]
Knowledge
Software
Etc.
Ces modules pourraient intégrer des Open Commmons Métiers ... Et donc être transversaux 5WH..

**Comment by iPlumb3r** [comment]
Dans les ontologies d'architecture d'entreprise on utilise 2 concepts pour cela :

**Comment by GuillaumeAV** [comment]
Je ne comprends même plus ma proposition et la proposition de @iPlumb3r est déja intégrée, du coup je ferme ;)
