### ISSUE TITLE
Ajouter notions "soutenu par" et "inspiré par"

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/pair#76]
Dans le cadre de [Reconnexion](https://reconnexion.app), nous travaillons sur un serveur ActivityPub à destination du mouvement Colibris. Ce serveur est en ligne depuis quelques mois déjà, mais nous travaillons maintenant à le rendre complètement sémantique via SemApps, en nous appuyant sur l'ontologie PAIR.

La mission de Colibris est d'**inspirer, relier et soutenir**. Ces notions sont très importantes. Et au sein des données que nous souhaitons mettre en valeur dans le cadre des groupes locaux Colibris, il serait très important que l'on puisse indiquer que:

- Un projet est _soutenu par_ une personne ou une organisation
- Une organisation est _soutenue par_ une autre organisation
- Une personne est _inspirée par_ une autre personne, une organisation ou un projet
- Une organisation est _inspirée par_ une autre organisation ou un projet
- Un projet est _inspiré par_ un autre projet.

Bref, vous comprenez l'idée... ;-) 

Au-delà de Colibris, il nous semble que ce sont des notions importantes à valoriser, afin de montrer la richesse des liens entre les P.A.I.R.

Qu'en dites-vous ?

(En anglais ça donnerait `inspiredBy` et `supportedBy`.)

**Comment by iPlumb3r** [comment]
Intéressant. Pour info, dans le modèle E2M, il existe une relation "valuates / valuated by"

**Comment by GuillaumeAV** [comment]
Yop ! C'est marrant, Alice voulait aussi rajouter la relation inspiré par ! 
Du coup c'est bon j'ai ajouté "inspired by" avec un alternative label "valuated by"
Et aussi une relation "suppported by" ;-)

**Comment by GuillaumeAV** [comment]
Fait :)
