### ISSUE TITLE
Intégrer la notion d'actualité dans le modèle PAIR

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#8]
Actualité d'un projet, d'un acteur, d'une idée, d'une ressource. 

Spontanément, je les classerais dans "Ressource" / "Ressource documentaire"

Dans les propriétés, les notions de date et de chronologie seraint centrales ...

**Comment by Septentrion** [comment]
Un exemple, peut-être pour savoir de quoi l'on parle ?

Je signale au passage que j'ai tenté d'intégrer dans l'ontologie une dimension temporelle avec la notion d'événement (évidemment pas dans le sens, dévoyé, de « *manifestation* »), mais que cela a disparu de la version finale **sans trace de discussion**.

Il me semble que c'est la question que tu poses. « *Actualité* » me semble, là aussi, un terme mal choisi. D'une part, c'est très connoté « *people* » (donc paresse intellectuelle de la presse magazine) ; d'autre part, par définition, ce qui est l'actualité d'un moment ne l'est plus du jour suivant et donc on introduit quelque chose qui est inconsistant, sémantiquement parlant.

Sinon, je dirais que, pour moi, ce qui supporte la dimension temporelle dans l'ontologie PAIR, c'est clairement **Projet**.

**Comment by GuillaumeAV** [comment]
3 ans après ... :-) 

L'idée serait  je crois d'avoir un fil d'actus et des notifications autour des actualités des Pairs ... 
Par exemple, Michel est devenu ami avec Thomas... Bernard a publié le document "release du MSC Pair" .. 
Donc peut être que la notion d'actualité "en soi" est superflue, et qu'il faut juste un fil d'actus et des notifications ..

**Comment by tfrancart** [comment]
C'est de l'ActivityStream et cela pose la question de l'articulation de PAIR avec ActivityStream

**Comment by GuillaumeAV** [comment]
A discuter à la review !

**Comment by GuillaumeAV** [comment]
Remplacé par #174
