### ISSUE TITLE
Statut/état d'un projet

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/pair#85]
Toujours dans le cadre du [serveur ActivityPub pour le mouvement Colibris](https://github.com/assemblee-virtuelle/pair/issues/76), nous avons besoin de donner un statut aux projets. Nous avons pour le moment 4 statuts:

- En réflexion
- En cours
- En sommeil
- Abandonné

Je pense utiliser le prédicat [tag](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tag) d'ActivityStreams pour "tagger" les projets, mais il faudrait que cela soit lié à une ressource, avec un type particulier, or il n'y a rien de tel dans l'ontologie ActivityStreams.

Avez-vous une idée de comment on pourait gérer ça dans le cadre de l'ontologie PAIR ? Ou bien est-ce que ça sort du cadre ?

**Comment by srosset81** [comment]
J'imagine qu'on pourrait aussi parler d'**état** (_state_)

**Comment by GuillaumeAV** [comment]
Helloo !

Je viens d'intégrer la notion de statut, en créant : 

- Une classe Status
   - Des sous classes Status : ProjectOrActivity / Idea / Event / Agent / Document / Task **-Status**
- Des propriétés inverses l'une de l'autre
   - hasProjectOrActivityStatus / hasIdeaStatus / ...
   - projectOrActivityStatusOf / ideaStatusOf / ... 
- Des individus 
   - Pour ProjectOrActivityStatus : 
      - En réflexion
      - En cours
      - En sommeil
      - Abandonné

Qu'en pensez vous @iPlumb3r @srosset81 @tfrancart ?

Vous pouvez vous jouer sur protege 3.5 en y chargeant [l'ontologie](https://github.com/assemblee-virtuelle/pair/tree/PAIR_Summer_2020_Release_WIP/2-Implementation) ;-)

**Comment by iPlumb3r** [comment]
Peut-être une unique Object Property "hasStatus" (Domain = ProjectOrActivity or Idea or Event or Agent or Document or Task  / Range = Status) aurait suffit ?

**Comment by GuillaumeAV** [comment]
Ben si tu vas voir les instanciations, il y a de vrais spécificités, du cpup je me dis que c'est pertinent de distinguer les trucs ;-)

**Comment by tfrancart** [comment]
1. Status devrait être sous Concept.
2. Je ne sais si c'est le rôle de PAIR de fournir des instances/valeurs possibles de Status. Chaque utilisateur/projet peut se définir ses valeurs; en définissant une liste possible de valeurs, il y a toujours le risque que ca ne convienne pas à un utilisateur en particulier.
3. Ce n'est pas parce qu'il y a des sous-classes de Status (AgentStatus, EventStatus, etc.) qu'il faut forcément qu'il y ait autant de proprétés de status; pour moi ça n'a pas de sens, un truc à un statut, c'est le même sens / la même sémantique que ce truc soit un projet ou un évènement. Donc une seule proprété hasStatus et des restrictions locales

![image](https://user-images.githubusercontent.com/2728945/81583328-80f11880-93b1-11ea-83e5-7c538dc36bca.png)

4. Il faut éviter les propriétés inverses genre "agentStatusOf", etc. Ces propriétés inverses sont dangeureuses, longues à paramétrer et n'apportent rien.

**Comment by tfrancart** [comment]
Je suis volontaire pour faire une PR là-dessus si ça vous dit

**Comment by GuillaumeAV** [comment]
Aah super ! Très bonne idée, merci Thomas !!

Le lun. 11 mai 2020 à 18:06, Thomas Francart <notifications@github.com> a
écrit :

**Comment by GuillaumeAV** [comment]
Fait :)
