### ISSUE TITLE
Une ontologie pour l'économie Circulaire 

### ISSUE THREAD

**Issue by Ancelin-AWA-AV** [assemblee-virtuelle/pair#87]
Par Ancelin Moulherat sur demande de Guillaume : référencer des cas d'usages et faire de la prospective SemApps & Web distribué.

Afin de gérer les échanges de ressources (récup) et de compétences (revalorisation des déchets) entre les acteurs de l'économie circulaire, dans une logique proche du Data Food Consortium, une ontologie de description des biens et services spécifiques de l'EC semble une priorité structurante pour la coopération des acteurs notamment les tiers-lieux (cc OASIS 21 !).

Carto 1 : 
http://materiauxreemploi.com/carte-acteurs-filiere-reemploi/?fbclid=IwAR2UW6LKrMiD69o0pO393onnpN0OsNAIFR865LYEMRjkmgwNtX1GZdzQdTY

(Volumes d'Oasis 21 y est impliqué)
http://morganmoinet.com/2018/10/25/pechakucha-volumes/?fbclid=IwAR0_TnJ883y7MWAOAjaDTmZI8NarDH-Lm9lvTMsAHkWGTIZdSlvTqGoJ_V4

(également Zéro Waste Festival)
http://morganmoinet.com/2018/06/29/festival-zero-waste/?fbclid=IwAR2dialHBwZwA8QytBIgV_tYjL8bPFTrZFWcA7Y2WRmscHTYWljk57hU_S8

Carto 2 (belge)
https://opalis.eu/fr

Un expert / figure de proue / tête de réseaux à contacter
https://www.facebook.com/morganlemercierm

La bénévole d'AWA qui va faire une carto des écofournisseurs pour l'architecture durable, l'habitat léger et l'autoconstruction.
https://www.facebook.com/aude.geant.3

**Comment by Ancelin-AWA-AV** [comment]
@GuillaumeAV  
Et voilà première contribution :)

**Comment by GuillaumeAV** [comment]
Super merci beaucoup @Ancelin-AWA-AV je vais explorer tout ça dans les prochains jours ;-)

**Comment by iPlumb3r** [comment]
A chaud, j’aurais tendance à dire que le domaine de l’économie « circulaire » ne se modélise PAS différemment de celui de l’économie « classique » !

C'est juste que la circularité émergera du chainage des relations :
   - Agent > produces > Deliverable
   - Deliverable > consumed by > Agent
