### ISSUE TITLE
Type d'événement a t'il sa place comme classe ? 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#9]
N'est ce pas plutôt une sous classe de thème ou de concept ? Ou alors, événement n'est il pas une sous-classe de type d'événement ? On peut aussi se faire la même réflexion au sujet des domaines d'activités ... Je propose de les mettre en sous classes de skos concept ... Vous pourrez modifier ;-)

**Comment by tfrancart** [comment]
Summer2019 : c'est exactement ce qu'on a fait, OrganizationType ou PlaceType sont déclarés sous-classes de skos:Concept, il pourrait en être de même pour un potentiel EventType (qui n'existe pas pour l'instant).
