### ISSUE TITLE
Lister les différents types d'affiliation entre agents 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/pair#91]
Sous la forme d'un tableau à double entrée pour déterminer si on a besoin d'instancier un rôle par type d'agent ou si un role suffit pour tous les types d'agents

**Comment by GuillaumeAV** [comment]
Suite à une discussion qu'on vient d'avoir avec Thomas une perspective pourrait être d'avoir une seule classe (role) pour gérer les types d'affilliation puis utiliser les "restrictions" pour spécifier quels types d'affiliations s'appliquent à tels types d'agents ?
 
Avantage : la légèreté de l'ontologie, sa plus grande facilité d'instanciation. 
Inconvénient : Je ne vois pas trop ...

@iPlumb3r  @ReX-AV-Gab @tfrancart

**Comment by iPlumb3r** [comment]
Je pensais que les restrictions ne pouvoir s'appliquer qu'aux Domain et Range d'un ObjectProperty ... je ne savais pas que cela pouvais s'appliquer des listes d'individus ... mais si c'est possible alors il s'agit effectivement d'une solution plutôt élégante !

**Comment by GuillaumeAV** [comment]
Aah oups désolé, j'ai surinterprêté je crois ! En effet on en a discuté à propos des propriétés hasPart / partOf

**Comment by iPlumb3r** [comment]
Il me semble effectivement que l'on échappera pas à plusieurs Classes du type "AffiationRole4Group", "AffiationRole4Organization" et "AffiationRole4Ecosystem" ... 
... avec pour chacun les valeurs qui vont bien.
