### ISSUE TITLE
Sous-propriétés de hasPart et isPartOf : inutile, faire des restrictions locales.

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#96]
Ne pas faire ça :

![image](https://user-images.githubusercontent.com/2728945/81583882-48057380-93b2-11ea-8115-2a4cb6c8dea9.png)

Utiliser une seule propriété hasPart, qui devrait avoir comme domain et range la classe Subjet, et faire des restrictions locales.

**Comment by babonet13** [comment]
Effectivement, 1 seule ObjectProperty "hasPart" doit suffire ...

**Comment by iPlumb3r** [comment]
Effectivement, 1 seul ObjectProperty "hasPart" doit suffire
