### ISSUE TITLE
Décaler les sous-classes de Ressource (ex. Tutorial, Currency, etc.) comme des ResourceType sous Concept

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/pair#99]

**Comment by GuillaumeAV** [comment]
@iPlumb3r ca te semble bien ?

**Comment by iPlumb3r** [comment]
Impossible à dire si c'est bien dans l'absolu ;-)
=> cela dépends du niveau de gestion que tu souhaite avoir sur ces concepts !

Je dirais qu'on est on est ici sur une problématique similaire à celle de la gestion - par exemple - des University

De 2 choses l’une :
   - Cas A : S’il est « essentiel » de gérer des « University » dans PAIR, alors gère « University » comme une Sous-Classe de la Classe « Organization »
   - Cas B : Si ce n’est pas « essentiel », mais seulement « utile »,  alors on gère « University » comme un Individu de la Classe « OrganizationType »
> Nous avions tranché ensemble que nous étions dans le Cas B


Et bien pour les « Resource », c’est pareil !
(Exemple avec « Atom-Based Resource »)
De 2 choses l’une :
   - Cas A : S’il est « essentiel » de gérer des « Atom-Based Resource » dans PAIR, alors gère « Atom-Based Resource » comme une Sous-Classe de la Classe « Resource »
   - Cas B : Si ce n’est pas « essentiel », mais seulement « utile »,  alors on gère « Atom-Based Resource » comme un Individu de la Classe « ResourceType »

Il reste maintenant à déterminer qu’est ce qui nous permet de trancher !
Par exemple, on peux imaginer qu’une Atom-Based Resource est caractériser par un « Poids » ou une « Densité » (ou autre chose)
=> Est-ce important de gérer cela ?
Si oui, alors il faut gérer ce concept comme une Classe
Si non, alors il « suffit de gérer ce concept comme un Individu de la Classe ResourceType

**Comment by GuillaumeAV** [comment]
Oups je ne sais plus ce qu'on s'était dit, mais je crois en effet que basculer en resourcetype permettrait d'alléger et de flexibiliser le truc  ! Pas besoin je crois de rentrer dans le détai, mais plutôt viser la généricité .. Comme pour les Acteurs en effet ...
